batch_size: 10
data_path: ./mimic-data/
dropout: 0.2
embedding_size: 768
eval_freq: 1
excluded_features: 0
leaky_relu_alpha: 0.1
lr: 0.0001
manual_seed: 0
mask_prob: 0.1
num_of_epochs: 10
num_of_heads: 1
num_of_layers: 2
overwrite_save: false
reg_method: l2
reg_weight: 1e-2
result_path: ./VGNN/
save_model: true
test: false
upsample_factor: 2
var: true
var_scale: 0.001
weight_decay: 1e-2
